### ISSUE TITLE
Support for pre-chorus in .txt format

### ISSUE THREAD

**Issue by fartleako** [reckel-jm/cantara#17]
Currently, a pre-chorus is not supported with the ccli song format. If you change it to a .song format it works fine. 

The pre-chorus should be displayed before the chorus itself.

 - OS: Windows
 - Version 2.4.0

To try it out yourself, you can open up the included file below. You will see that the pre-chorus is not displayed (just verse 1 - chorus - verse 2).

[Lorem ipsum dolor.txt](https://github.com/reckel-jm/cantara/files/11830638/Lorem.ipsum.dolor.txt)

**Comment by reckel-jm** [comment]
Thanks for posting! cdd34c5920be620cf1df1a27b6b01ee50a4eed91 implements a fix which produces the desired outcome:

```
#ccli-songnumber: 000000
#author: Lorem Ipsum
#ccli-licensenumber: 000000

Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam

Missing Pre-Chorus
Missing Pre-Chorus

eirmod tempor invidunt ut labore 
et dolore magna aliquyam
eirmod tempor invidunt ut labore 
et dolore magna aliquyam

erat, sed diam voluptua. 
At vero eos et accusam et
sed diam

Missing Pre-Chorus
Missing Pre-Chorus

eirmod tempor invidunt ut labore 
et dolore magna aliquyam
eirmod tempor invidunt ut labore 
et dolore magna aliquyam      
```

**Comment by reckel-jm** [comment]
The issue is solved and therefore can be closed.

**Comment by reckel-jm** [comment]
The issue is solved and therefore can be closed.
